version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  redis:
    image: redis:7.0.8-alpine
    ports:
    - 6379:6379

  mongo:
    image: mongo
    restart: always
    expose:
      - ${MONGODB_PORT}
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}

  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - app-network
    volumes:
      - ./.cache/pgdata:/var/lib/postgresql
